### ISSUE TITLE
thanks you

### ISSUE THREAD

**Issue by achengfu** [jtborn/TFT-Overlay#10]
thanks you (ﾉﾟ▽ﾟ)ﾉ

**Comment by jtborn** [comment]
You're welcome! :)

**Comment by sunuanxiaopy** [comment]
> thanks you (ﾉﾟ▽ﾟ)ﾉ

你这个版本下载的下来吗？为什么我一点速度都没有。。。
Did you download this version? Why don't I have any speed...

**Comment by achengfu** [comment]
> > thanks you (ﾉﾟ▽ﾟ)ﾉ
> 
> 你这个版本下载的下来吗？为什么我一点速度都没有。。。
> Did you download this version? Why don't I have any speed...

可以啊，你需要科学上网，速度会快点

**Comment by sunuanxiaopy** [comment]
之前下载的飞快...嘶..谢谢 那我再试试
