### ISSUE TITLE
Add Qiyana and Lux to Origins

### ISSUE THREAD

**Issue by SuTree** [jtborn/TFT-Overlay#12]
Hi, 

我建议把奇亚娜和拉克丝都加入进种族羁绊里面。
I recommend adding both Qiyana and Lux to Origins.

Qiyana 有四种元素化身，lux有十种。TFT节奏非常快，需要很直观的参考。
Qiyana has four avatars and ten lux. TFT rhythm is very fast and requires a very intuitive reference.

**Comment by jtborn** [comment]
Thanks for the recommendation. I had thought about adding them to every origin they applied but wasn't sure if people would like that so I left them as "Variable". But I think you're right, I will add them to every applicable origin.

感谢您的推荐。 我曾考虑过将它们添加到他们应用的每个来源中，但是不确定人们是否愿意，所以我将其保留为“变量”。 但是我认为您是对的，我会将它们添加到每个适用的来源中。

(That's from Google Translate, let me know if that helps or if there's a better translating service)

**Comment by jtborn** [comment]
I've just pushed an update that addresses this issue. Qiyana and Lux are now both added to each element that they can spawn as. :)

**Comment by SuTree** [comment]
good!
