### ISSUE TITLE
Cost value bug

### ISSUE THREAD

**Issue by SuTree** [jtborn/TFT-Overlay#14]
Hi,

I found some cost values wrong in Elements table and  Classes table.

- Elements

|  Elements | chess  | chess | 
| --- | --- | --- |
|Inferno|Diana|
|Light|Vayne|
|Ocean|Thresh|Nautilus|
|Shadow|Kindred|Malzahar|
|Steel|Rek'Sai|Nocturne|

----
- Classes

| Classes | chess | chess | chess | chess |
| --- | --- | --- | --- | --- |
|Avatar|Lux|
|Druid|Maokai|
|Mage|Syndra|
|Mystic|Soraka|Janna|Master Yi|Nami|
|Ranger|Vayne|
|Summoner|Azir|Annie|Yorick|Zed|
|Warden|Taric|

**Comment by jtborn** [comment]
Wow, idk how I missed so many... I think I originally set these values as the information was coming out and then Riot finalized the data and changed some costs and I forgot to double check them. Or all the copy pasting and editing values got to me, either way my bad. Thank you for catching those.
