### ISSUE TITLE
Brand is missing in Elements table

### ISSUE THREAD

**Issue by SuTree** [jtborn/TFT-Overlay#15]
昨天我用三星布兰德吃鸡了，太酷了，一个技能清场。
Yesterday I got No.1 with a 3 star brand. It's so cool. a skill clearance.

所以让我发现了这个问题，布兰德没有在种族羁绊页。
So let me find this problem， Brand is not in Elements table。

我对比了2.2.x历史版本发现都没有布兰德。
I compared the 2.2.x version and found that there is no brand.

---
感谢一直更新。
Thanks for updating.

**Comment by jtborn** [comment]
This will be added in the Patch 9.23 update. Thanks.

**Comment by SuTree** [comment]
It's OK.
