### ISSUE TITLE
New game version

### ISSUE THREAD

**Issue by 1055169799** [jtborn/TFT-Overlay#16]
Hello author, the new game version is already online, will this software continue to be updated?
————
作者你好，新的游戏版本已经上线，这个软件还会继续更新吗？

**Comment by xiaozeBUFF** [comment]
The author wants to update the new version, thank you

**Comment by xiaozeBUFF** [comment]
Can you update it recently

**Comment by jtborn** [comment]
Sorry for the delay, I'm updating it now. Will be available in a couple hours.

**Comment by jtborn** [comment]
New version now available. I still need someone to update the Chinese translations for the new items and classes/origins.

**Comment by ZhiGuoZheng** [comment]
> New version now available. I still need someone to update the Chinese translations for the new items and classes/origins.

Thanks for update~
