### ISSUE TITLE
New version of S2

### ISSUE THREAD

**Issue by WigeHuang** [jtborn/TFT-Overlay#6]
Does this support a new version of the US service?

**Comment by jtborn** [comment]
Ah, I never pushed the 9.21 update as I was working on the Set 2 changes in a new branch. I can push that when I get home from work.

**Comment by jtborn** [comment]
If you mean Set 2, yes I'm working on the set 2 changes. Everything is just about ready, still waiting on the artwork for some of the new items.

**Comment by WigeHuang** [comment]
That's fine, thanks
